version: '3.7'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.2.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - elastic-stack
  kibana:
    container_name: kibana
    image: kibana:7.2.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic-stack
  logstash:
    container_name: logstash
    image: logstash:7.2.0
    ports:
      - "5044:5044"
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_MONITORING_ENABLED=true
    networks:
      - elastic-stack
    volumes:
      - ./elastic-stack/logstash.conf:/etc/logstash/conf.d/logstash.conf:ro
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.2.0
    networks:
      - elastic-stack
    volumes:
      - ./elastic-stack/filebeat.yml:/etc/filebeat/filebeat.yml:ro

networks:
  elastic-stack:
    name: elastic-stack
    driver: bridge
